create table if not exists public.podio_enquiries (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  email text not null,
  phone text,
  enquiry_type text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.podio_consents (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  child_name text not null,
  email text not null,
  general_participation boolean not null default false,
  recording_consent boolean not null default false,
  photo_consent text,
  communication_consent boolean not null default false,
  signature text not null,
  submitted_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.podio_event_registrations (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  event_slug text not null,
  full_name text not null,
  age integer not null,
  email text not null,
  phone text not null,
  school_or_organization text,
  city text,
  parent_name text,
  parent_email text,
  parent_phone text,
  parent_relationship text,
  payment_status text not null default 'free',
  created_at timestamptz not null default now()
);

create index if not exists idx_event_registrations_slug on public.podio_event_registrations(event_slug);
create index if not exists idx_event_registrations_ref on public.podio_event_registrations(reference);

