create table if not exists public.podio_enquiries (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  email text not null,
  phone text,
  enquiry_type text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.podio_consents (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  child_name text not null,
  email text not null,
  general_participation boolean not null default false,
  recording_consent boolean not null default false,
  photo_consent text,
  communication_consent boolean not null default false,
  signature text not null,
  submitted_date text,
  created_at timestamptz not null default now()
);
